/* eslint-disable no-underscore-dangle */

export const FETCH_USER_REQUEST = 'FETCH_USER_REQUEST';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_ERROR = 'FETCH_USER_ERROR';
export const SET_USERNAME = 'SET_USERNAME';

export const FETCH_ALL_COURSES_REQUEST = 'FETCH_ALL_COURSES_REQUEST';
export const FETCH_ALL_COURSES_SUCCESS = 'FETCH_ALL_COURSES_SUCCESS';
export const FETCH_ALL_COURSES_ERROR = 'FETCH_ALL_COURSES_ERROR';

declare const CLIENT_SIDE_RENDERING: string;
const _CLIENT_SIDE_RENDERING = CLIENT_SIDE_RENDERING;
export { _CLIENT_SIDE_RENDERING as CLIENT_SIDE_RENDERING };
